import { Track } from '../types/audio';

export const SAMPLE_TRACKS: Track[] = [
  {
    id: 'track-1',
    title: 'Neon Horizon',
    artist: 'CYBERPULSE',
    album: 'Odyssey 2099',
    duration: 194,
    genre: 'Synthwave',
    year: 2024,
    accentColor: '#00f2fe',
    mood: 'Energy',
    bpm: 124,
    artwork: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=synthwave-80s-110045.mp3',
    lyrics: [
      { time: 0, text: '[Instrumental Intro - Analog Arpeggio]' },
      { time: 14, text: 'Midnight lights along the coastal grid' },
      { time: 22, text: 'Chasing shadows where the skyline hid' },
      { time: 30, text: 'Electric pulse, the engines hum tonight' },
      { time: 38, text: 'We break away into the violet light' },
      { time: 46, text: 'Zero gravity, no turning back' },
      { time: 54, text: 'Speed of sound along the endless track' },
      { time: 64, text: 'Neon horizon, guide our way' },
      { time: 72, text: 'Beyond the edge of yesterday' },
      { time: 82, text: '[Synth Solo & Percussion Drop]' },
      { time: 104, text: 'Signals flashing through the atmosphere' },
      { time: 112, text: 'In the resonance, the path is clear' },
      { time: 120, text: 'Take the wheel, surrender to the flow' },
      { time: 130, text: 'Where the neon currents glow' },
      { time: 142, text: 'Neon horizon, burning bright' },
      { time: 154, text: 'We dissolve into the night' },
      { time: 170, text: '[Outro Fade]' },
    ],
  },
  {
    id: 'track-2',
    title: 'Midnight Rain in Shibuya',
    artist: 'Komorebi & Sora',
    album: 'Tokyo Tape Sessions',
    duration: 168,
    genre: 'Lo-Fi',
    year: 2024,
    accentColor: '#9d4edd',
    mood: 'Chill',
    bpm: 82,
    artwork: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=lofi-study-112191.mp3',
    lyrics: [
      { time: 0, text: '[Vinyl Crackle & Gentle Rain on Glass]' },
      { time: 12, text: 'Drops descending through the lantern glow' },
      { time: 24, text: 'Gentle footsteps in the street below' },
      { time: 36, text: 'A cup of tea, a quiet room to think' },
      { time: 48, text: 'Time suspended on a peaceful brink' },
      { time: 60, text: '[Warm Electric Piano Chords]' },
      { time: 74, text: 'Let the rhythm wash the noise away' },
      { time: 88, text: 'Finding solace at the close of day' },
      { time: 102, text: 'Raindrops falling in Shibuya' },
      { time: 118, text: 'Quiet reverie...' },
      { time: 134, text: '[Soft Muffled Trumpet Melodies]' },
      { time: 150, text: '[Rain fades gently into distance]' },
    ],
  },
  {
    id: 'track-3',
    title: 'Deep Quantum Drift',
    artist: 'Aetheria Protocol',
    album: 'Cosmic Resonance',
    duration: 220,
    genre: 'Ambient',
    year: 2023,
    accentColor: '#00b4d8',
    mood: 'Focus',
    bpm: 70,
    artwork: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=ambient-piano-amp-strings-10711.mp3',
    lyrics: [
      { time: 0, text: '[Sub-bass swell & deep harmonic resonance]' },
      { time: 28, text: 'Entering the neutral density corridor' },
      { time: 56, text: 'Frequency alignment achieved' },
      { time: 84, text: 'Expanding into pure focus' },
      { time: 120, text: 'All boundaries dissolve in acoustic space' },
      { time: 160, text: 'Deep quantum equilibrium' },
      { time: 195, text: '[Harmonic tail decay]' },
    ],
  },
  {
    id: 'track-4',
    title: 'Solar Flare',
    artist: 'HyperDrive',
    album: 'Supernova',
    duration: 208,
    genre: 'Electronic',
    year: 2024,
    accentColor: '#ff9e00',
    mood: 'Workout',
    bpm: 130,
    artwork: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_0625c1539c.mp3?filename=future-technology-11326.mp3',
    lyrics: [
      { time: 0, text: '[High Energy Pulse Build]' },
      { time: 15, text: 'Pressure rising, fuel ignited' },
      { time: 23, text: 'Core reactor fully sighted' },
      { time: 30, text: '3, 2, 1 - IGNITION' },
      { time: 32, text: '[Bass Drop & Driving Four-on-the-Floor]' },
      { time: 62, text: 'Push the limit past the red line' },
      { time: 78, text: 'Faster than the speed of light' },
      { time: 94, text: 'Feel the solar flare!' },
      { time: 120, text: '[Sub Drop & Arp Climax]' },
      { time: 150, text: 'No stopping now' },
      { time: 180, text: '[Maximum Velocity Outro]' },
    ],
  },
  {
    id: 'track-5',
    title: 'Elysium Nocturne',
    artist: 'Valeria Vance',
    album: 'Silhouettes in Minor',
    duration: 186,
    genre: 'Classical',
    year: 2023,
    accentColor: '#f72585',
    mood: 'Melancholy',
    bpm: 66,
    artwork: 'https://images.unsplash.com/photo-1520523839898-50712825e3a7?w=800&auto=format&fit=crop&q=80',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/02/07/audio_bf491dc67b.mp3?filename=sad-piano-ambient-10776.mp3',
    lyrics: [
      { time: 0, text: '[Concert Grand Piano - Solo Cadence]' },
      { time: 22, text: 'Notes written on parchment in the dusk' },
      { time: 44, text: 'Memories lingering in quiet rooms' },
      { time: 68, text: 'A haunting melody from another lifetime' },
      { time: 95, text: 'Strings enter softly like a whispered remembrance' },
      { time: 130, text: 'The resolution we could never find' },
      { time: 165, text: '[Final gentle keystroke]' },
    ],
  },
  {
    id: 'track-6',
    title: 'Celestial Dawn',
    artist: 'Aurora Collective',
    album: 'Prism Horizons',
    duration: 215,
    genre: 'Dreamwave',
    year: 2024,
    accentColor: '#10b981',
    mood: 'Travel',
    bpm: 108,
    artwork: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_c230e17d04.mp3?filename=relaxed-vlog-131746.mp3',
    lyrics: [
      { time: 0, text: '[Breeze, Windchimes & Shimmering Pads]' },
      { time: 20, text: 'Morning breaks above the golden valley' },
      { time: 40, text: 'Sunlight scattering across the mountain ridges' },
      { time: 65, text: 'Every horizon is a new beginning' },
      { time: 90, text: 'We breathe in the endless air' },
      { time: 125, text: 'Follow the light wherever it leads' },
      { time: 160, text: 'Celestial dawn has come' },
      { time: 190, text: '[Ethereal vocalise fade]' },
    ],
  }
];

export const GENRES = ['All', 'Synthwave', 'Lo-Fi', 'Ambient', 'Electronic', 'Classical', 'Dreamwave'];
export const MOODS = ['Focus', 'Chill', 'Energy', 'Workout', 'Sleep', 'Melancholy', 'Travel', 'Deep work'];
